grid components added
vuejs-norte/puto-framework pull request #14
Opened 2019-10-04 10:20 UTC by oskar-kupski-elpassion

#9 Remember to run `npm install` (scss and bootstrap 4 grid were added). You can configure grid for your needs in `src/components/grid/_grid.scss` file: breakpoints, max-widths, columns and gutter

2019-10-07 20:45 UTC, lubien requested changes
Don't modify our package{-lock}.json files :)

2019-10-07 20:45 UTC, lubien commented on package.json
> +    "bootstrap-4-grid": "^3.1.1",
From https://github.com/vuejs-norte/puto-framework/issues/9#issuecomment-538069197

> this is a HTML-only framework 

No CSS allowed :)

> just put classes on divs

You did that already!

2019-10-07 20:45 UTC, lubien commented on src/App.vue
>    <div id="app">
Please don't do **anything** in this file

You need to create examples on `stories/` (look how other people did some)

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PCol.vue
> +  <div v-bind:class="[`col-${sizeXs}`,`col-sm-${sizeSm}`,`col-md-${sizeMd}`,`col-lg-${sizeLg}`,`col-xl-${sizeXl}`]">
`v-bind:class`

`:class`

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PCol.vue
> +  <div v-bind:class="[`col-${sizeXs}`,`col-sm-${sizeSm}`,`col-md-${sizeMd}`,`col-lg-${sizeLg}`,`col-xl-${sizeXl}`]">
Also please make a computed property called `classNames`.

If there is no `sizeXs` **don't** add `col-xs-undefined`.

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PCol.vue
> +<style scoped lang="scss">
No CSS

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PCol.vue
> +  <div v-bind:class="[`col-${sizeXs}`,`col-sm-${sizeSm}`,`col-md-${sizeMd}`,`col-lg-${sizeLg}`,`col-xl-${sizeXl}`]">
All class names should start with `puto-`

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PContainer.vue
> +  <div v-bind:class="[fluid ? 'container-fluid' : 'container']">
`class`

All class names should start with `puto-`

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PContainer.vue
> +    <div class="row">
?

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PContainer.vue
> +<style scoped lang="scss">
No CSS

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PRow.vue
> +  <div class="row">
All class names should start with `puto-`

2019-10-07 20:45 UTC, lubien commented on src/components/grid/PRow.vue
> +<style scoped lang="scss">
No CSS

2019-10-07 20:45 UTC, lubien commented on src/components/grid/_grid.scss
> +$grid-breakpoints: (
No CSS

2019-10-07 20:45 UTC, lubien commented
> Also please keep in mind that I am newbie to Vue, so if anything is incorrect let me know

Sure, let's do it together

2019-10-09 08:10 UTC, oskar-kupski-elpassion commented on package.json
> +    "bootstrap-4-grid": "^3.1.1",
So I should add classess to divs, but how should I style the divs without using css? Also where should I store information about media breakpoints? Should it be in css or dynamiclly calculated via js ?

2019-10-09 10:28 UTC, oskar-kupski-elpassion commented
I've done some refactoring, please let me know it it works you better

2019-10-09 11:33 UTC, lubien commented on src/components/grid/PCol.vue
> +    className() {
Update to be like https://github.com/vuejs-norte/puto-framework/blob/master/src/components/PButton.vue#L40-L46

2019-10-09 11:33 UTC, lubien commented on stories/PGrid.stories.js
> +    template: `<PContainer>
Let's indent like this:

```js
    template: `<PContainer>
      <PRow>
        <PCol :size-sm="10" :size-lg="12">COLUMN</PCol>
        <PCol :size-md="10" :size-xl="12">COLUMN</PCol>
        <PCol :size-xs="10" :size-lg="12">COLUMN</PCol>
      </PRow>
      <PRow>
        <PCol :size-xs="10" :size-lg="12">COLUMN</PCol>
      </PRow>
    </PContainer>`
  })

```

2019-10-09 11:33 UTC, lubien commented on stories/PGrid.stories.js
> +    template: `<PContainer fluid>
Same indent

2019-10-09 11:33 UTC, lubien commented on package.json
> +    "bootstrap-4-grid": "^3.1.1",
The styles are out of the scope of this framework. It's meant to be a HTML-only POC framework that you would implement stuff like that later.

We really need that info on our repo (there's an issue for this)

2019-10-09 11:35 UTC, lubien requested changes
Just one last review

2019-10-09 14:15 UTC, oskar-kupski-elpassion commented
done and pushed :)

2019-10-09 14:17 UTC, lubien approved these changes

2019-10-09 14:17 UTC, merged

2019-10-09 14:18 UTC, lubien commented
Thank you :3