Added MIT License
vuejs-norte/puto-framework pull request #15
Opened 2019-10-07 01:34 UTC by rsomlette

## Description

Added the MIT License to the package.json

https://github.com/vuejs-norte/puto-framework/issues/1

2019-10-07 20:25 UTC, lubien requested changes
Please, also create a LICENSE.md file properly editing the top to "VueJS Norte" organization on the name of "Puto Framework"

2019-10-08 17:03 UTC, rsomlette commented
@lubien added the license following GitHub sample license which mention a company name which in the present case is `VueJS Norte`

2019-10-09 10:58 UTC, lubien approved these changes

2019-10-09 10:58 UTC, lubien commented
Thank you!

2019-10-09 10:58 UTC, merged