basic pagination component
vuejs-norte/puto-framework pull request #21
Opened 2019-10-10 10:43 UTC by oskar-kupski-elpassion

#17 Please let me know if that is what you had in mind

2019-10-14 21:29 UTC, lubien commented
![image](https://user-images.githubusercontent.com/9121359/66784311-766cb000-eeb0-11e9-8820-11b992391298.png)

Oh I'm sorry. I've reviewd but didnt send it!

2019-10-14 21:29 UTC, lubien requested changes

2019-10-14 21:29 UTC, lubien commented on src/components/PPagination.vue
> +    const blockClassName = 'puto-pagination'
If this never changes, put directly on template

2019-10-14 21:29 UTC, lubien commented on src/components/PPagination.vue
> +    const itemBaseClassName = `${blockClassName}__item`
`puto-pagination-item`

2019-10-14 21:29 UTC, lubien commented on src/components/PPagination.vue
> +      linkClassName: `${blockClassName}__link`,
`puto-pagination-link`

2019-10-14 21:29 UTC, lubien commented on src/components/PPagination.vue
> +      prevLabel: '<',
This and nextLabel would be nice to be a prop.

Also don't abbreviate, use `previousLabel` please

2019-10-14 21:29 UTC, lubien commented on src/components/PPagination.vue
> +      firstPage: 1
Weird. Why this?

2019-10-14 21:29 UTC, lubien commented on src/components/PPagination.vue
> +        this.value === page && `${this.itemBaseClassName}--active`
`puto-pagination-item-active`

2019-10-14 21:29 UTC, lubien commented on src/components/PPagination.vue
> +    itemClassName(page) {
I think this is short enough to be directly on the template using `class=""` for static classes and `:classes="{ 'puto-pagination-item-active': CONDITION }`

2019-10-14 21:29 UTC, lubien commented on src/components/PPagination.vue
> +        @click.prevent="changePage(value - 1)"
Would changePage(-1) be possible to call?

2019-10-15 07:02 UTC, oskar-kupski-elpassion commented
Hi @lubien, unfortunately I won't be able to help anymore. Please unassign me

2019-10-15 07:04 UTC, lubien commented
> Hi @lubien, unfortunately I won't be able to help anymore. Please unassign me

No problem. Best regards. Hope to work with you again if possible.

2019-10-15 07:04 UTC, closed without merging